server:
  port: 8761
  servlet:
    context-path: /discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://www.writehere.kro.kr/discovery/
  instance:
    hostname: www.writehere.kro.kr
    prefer-ip-address: false
  server:
    eviction-interval-timer-in-ms: 30000